chore: add import sorting rule
ipfs/eslint-config-ipfs pull request #126
Opened 2023-01-31 19:32 UTC by SgtPooki

2023-02-01 13:42 UTC, achingbrain approved these changes
LGTM.  I don't love all the empty lines between groups of imports because you frequently have one lone import in a group which just looks weird sitting there all on it's own, but I don't hate them either.

I updated the title to be `feat!:` because feature will break linting for pretty much every project, though it's easy to fix.

One caveat is that `--fix` only moves the imports around - it doesn't move the accompanying `// @ts-expect-error no types` comments we have in lots of places above imports of modules that don't ship with types.

2023-02-13 19:37 UTC, SgtPooki commented
> One caveat is that --fix only moves the imports around - it doesn't move the accompanying // @ts-expect-error no types comments we have in lots of places above imports of modules that don't ship with types.

Yea, that's important. we could update the rule to support moving associated comments, but I haven't looked into that.

2023-02-28 08:49 UTC, achingbrain requested changes
A few suggestions to make this a bit simpler.

2023-02-28 08:49 UTC, achingbrain commented on ts.js
> +    ]
I think this section may be unnecessary as we extend the config from `js.js`?  At least running locally I can format `.ts` imports with the `.js` rules.

```suggestion
    'jsdoc/require-param-type': 'off' // allow compiler to derive param type
```

2023-02-28 08:49 UTC, achingbrain commented on ts.js
> +    'import'
I think this section may be unnecessary as we extend the config from `js.js`?  At least running locally I can format `.ts` imports with the `.js` rules.

```suggestion
    'etc'
```

2023-02-28 08:49 UTC, achingbrain commented on js.js
> +    ]
How about a bit simpler?  Built-ins, externals, types then everything else.

This way the externals are sorted in the same order as the deps in `package.json`.

The only outlier here I think is "object imports" but I'm not sure we use them anywhere.

```suggestion
    'import/order': [
      'error',
      {
        alphabetize: {
          order: 'asc',
          caseInsensitive: false
        },
        'newlines-between': 'always',
        // the overall order of imports - anything not in this list is grouped together at the end
        groups: ['builtin', 'external', 'type']
      }
    ]
```

2023-04-05 15:51 UTC, achingbrain approved these changes

2023-04-05 15:52 UTC, merged